# Build stage
FROM node:18-alpine as build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build --max-old-space-size=4096

# Run stage
FROM node:18-alpine as run

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/dist ./dist
COPY package*.json ./

RUN npm install --only=production && \
    rm package*.json

EXPOSE 8002

CMD ["node", "dist/main.js"]